// examples/react-vite/src/main.tsx
import { StrictMode, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { AutoGuideProvider, AutoGuideWidget, InspectorOverlay } from '@autoguide/react';

function App() {
  const [page, setPage] = useState<'home' | 'settings'>('home');

  return (
    <main style={{ fontFamily: 'system-ui, sans-serif', padding: 24 }}>
      <h1>AutoGuide Beispiel-App</h1>
      <nav style={{ display: 'flex', gap: 8, marginBottom: 16 }}>
        <button type="button" onClick={() => setPage('home')}>
          Start
        </button>
        <button type="button" onClick={() => setPage('settings')}>
          Einstellungen
        </button>
      </nav>
      {page === 'home' ? (
        <section>
          <p>Willkommen in der Referenz-App für AutoGuide.</p>
          <button type="button">Aktion speichern</button>
        </section>
      ) : (
        <section>
          <p>Einstellungen — zweite Route für Kontext-Tests.</p>
        </section>
      )}
    </main>
  );
}

createRoot(document.getElementById('root')!).render(
  <StrictMode>
    <AutoGuideProvider appId="example-react-vite" userRole="Admin">
      <App />
      <AutoGuideWidget />
      <InspectorOverlay />
    </AutoGuideProvider>
  </StrictMode>,
);

// examples/angular-vite/src/main.ts
import 'zone.js';
import { bootstrapApplication } from '@angular/platform-browser';
import { Component } from '@angular/core';
import {
  AutoGuideProvider,
  AutoGuideWidget,
  InspectorOverlay,
} from '@autoguide/angular';

@Component({
  selector: 'app-root',
  standalone: true,
  imports: [AutoGuideProvider, AutoGuideWidget, InspectorOverlay],
  template: `
    <ag-autoguide-provider appId="example-angular-vite" userRole="Admin">
      <main style="font-family: system-ui, sans-serif; padding: 24px">
        <h1>AutoGuide Angular Beispiel-App</h1>
        <p>Willkommen in der Angular-Referenz-App für AutoGuide.</p>
        <button type="button">Aktion speichern</button>
      </main>
      <ag-autoguide-widget />
      <ag-inspector-overlay />
    </ag-autoguide-provider>
  `,
})
class AppComponent {}

bootstrapApplication(AppComponent).catch(console.error);
