// plugins/react/src/AutoGuideProvider.tsx
/**
 * @autoguide/react — root provider for host applications.
 */

import type { ReactNode } from 'react';
import type { Fact, FlowRecord, PageRecord, VisibilityMode } from '@autoguide/core';
import { AutoGuideContext } from './context.js';

export interface AutoGuideProviderProps {
  appId: string;
  userRole?: string;
  mode?: VisibilityMode;
  route?: string;
  facts?: Fact[];
  pages?: PageRecord[];
  flows?: FlowRecord[];
  children: ReactNode;
}

export function AutoGuideProvider({
  appId,
  userRole,
  mode = 'development',
  route = typeof window !== 'undefined' ? window.location.pathname : '/',
  facts = [],
  pages = [],
  flows = [],
  children,
}: AutoGuideProviderProps) {
  return (
    <AutoGuideContext.Provider
      value={{ appId, userRole, mode, route, facts, pages, flows }}
    >
      {children}
    </AutoGuideContext.Provider>
  );
}

// plugins/svelte/src/AutoGuideProvider.svelte
<script lang="ts">
  /**
   * @autoguide/svelte — root provider for host applications.
   */
  import { setContext } from 'svelte';
  import type { Fact, FlowRecord, PageRecord, VisibilityMode } from '@autoguide/core';
  import { AUTO_GUIDE_KEY } from './context.js';

  export let appId: string;
  export let userRole: string | undefined = undefined;
  export let mode: VisibilityMode = 'development';
  export let route: string = typeof window !== 'undefined' ? window.location.pathname : '/';
  export let facts: Fact[] = [];
  export let pages: PageRecord[] = [];
  export let flows: FlowRecord[] = [];

  setContext(AUTO_GUIDE_KEY, {
    get appId() { return appId; },
    get userRole() { return userRole; },
    get mode() { return mode; },
    get route() { return route; },
    get facts() { return facts; },
    get pages() { return pages; },
    get flows() { return flows; },
  });
</script>

<slot />
