// plugins/angular/src/autoguide-provider.component.ts
/**
 * @iamthamanic/autoguide-angular — root provider for host applications.
 */

import { Component, Input, OnChanges, OnInit, inject } from '@angular/core';
import type { Fact, FlowRecord, PageRecord, VisibilityMode } from '@iamthamanic/autoguide-core';
import { AutoGuideContextService } from './context.js';

@Component({
  selector: 'ag-autoguide-provider',
  standalone: true,
  template: '<ng-content />',
  providers: [AutoGuideContextService],
})
export class AutoGuideProviderComponent implements OnInit, OnChanges {
  private readonly ctx = inject(AutoGuideContextService);

  @Input({ required: true }) appId!: string;
  @Input() userRole?: string;
  @Input() mode: VisibilityMode = 'development';
  @Input() route = typeof window !== 'undefined' ? window.location.pathname : '/';
  @Input() facts: Fact[] = [];
  @Input() pages: PageRecord[] = [];
  @Input() flows: FlowRecord[] = [];
  @Input() loading = false;
  @Input() error: string | null = null;
  @Input() onRetry?: () => void;

  ngOnInit(): void {
    this.syncContext();
  }

  ngOnChanges(): void {
    this.syncContext();
  }

  private syncContext(): void {
    this.ctx.appId = this.appId;
    this.ctx.userRole = this.userRole;
    this.ctx.mode = this.mode;
    this.ctx.route = this.route;
    this.ctx.facts = this.facts;
    this.ctx.pages = this.pages;
    this.ctx.flows = this.flows;
    this.ctx.loading = this.loading;
    this.ctx.error = this.error;
    this.ctx.onRetry = this.onRetry;
  }
}

export type AutoGuideProviderProps = {
  appId: string;
  userRole?: string;
  mode?: VisibilityMode;
  route?: string;
  facts?: Fact[];
  pages?: PageRecord[];
  flows?: FlowRecord[];
  loading?: boolean;
  error?: string | null;
  onRetry?: () => void;
};

// plugins/svelte/src/AutoGuideProvider.svelte
<script lang="ts">
  /**
   * @iamthamanic/autoguide-svelte — root provider for host applications.
   */
  import { setContext } from 'svelte';
  import type { Fact, FlowRecord, PageRecord, VisibilityMode } from '@iamthamanic/autoguide-core';
  import { AUTO_GUIDE_KEY } from './context.js';

  export let appId: string;
  export let userRole: string | undefined = undefined;
  export let mode: VisibilityMode = 'development';
  export let route: string = typeof window !== 'undefined' ? window.location.pathname : '/';
  export let facts: Fact[] = [];
  export let pages: PageRecord[] = [];
  export let flows: FlowRecord[] = [];
  export let loading = false;
  export let error: string | null = null;
  export let onRetry: (() => void) | undefined = undefined;

  setContext(AUTO_GUIDE_KEY, {
    get appId() { return appId; },
    get userRole() { return userRole; },
    get mode() { return mode; },
    get route() { return route; },
    get facts() { return facts; },
    get pages() { return pages; },
    get flows() { return flows; },
    get loading() { return loading; },
    get error() { return error; },
    get onRetry() { return onRetry; },
  });
</script>

<slot />
