// plugins/react/src/ReviewBadge.tsx
/**
 * @iamthamanic/autoguide-react — dev-only confidence and provenance badge for facts.
 */

import type { Fact } from '@iamthamanic/autoguide-core';
import { getReviewBadgeState } from '@iamthamanic/autoguide-ui';

export interface ReviewBadgeProps {
  fact: Fact;
  mode: 'development' | 'published';
}

export function ReviewBadge({ fact, mode }: ReviewBadgeProps) {
  const state = getReviewBadgeState(fact, mode);
  if (!state.visible) return null;

  return (
    <span
      title={state.title}
      style={{
        marginLeft: 6,
        fontSize: 12,
        fontWeight: 600,
        color: `var(${state.colorVar})`,
      }}
    >
      ({state.label})
    </span>
  );
}

// plugins/svelte/src/ReviewBadge.svelte
<script lang="ts">
  /**
   * @iamthamanic/autoguide-svelte — dev-only confidence and provenance badge for facts.
   */
  import type { Fact, VisibilityMode } from '@iamthamanic/autoguide-core';
  import { getReviewBadgeState } from '@iamthamanic/autoguide-ui';

  const { fact, mode } = $props<{ fact: Fact; mode: VisibilityMode }>();

  const state = $derived(getReviewBadgeState(fact, mode));
</script>

{#if state.visible}
  <span
    title={state.title}
    style:margin-left="6px"
    style:font-size="12px"
    style:font-weight="600"
    style:color={`var(${state.colorVar})`}
  >
    ({state.label})
  </span>
{/if}
