// plugins/svelte/src/PanelSkeleton.svelte
<script lang="ts">
  /**
   * @iamthamanic/autoguide-svelte — loading skeleton for Help Widget panel.
   */
</script>

<div aria-hidden="true">
  <div
    style="height:12px;width:70%;border-radius:4px;background:var(--ag-surface-muted);margin-bottom:10px"
  ></div>
  <div
    style="height:12px;width:100%;border-radius:4px;background:var(--ag-surface-muted);margin-bottom:10px"
  ></div>
  <div
    style="height:12px;width:85%;border-radius:4px;background:var(--ag-surface-muted);margin-bottom:10px"
  ></div>
</div>

// plugins/react/src/PanelSkeleton.tsx
/**
 * @iamthamanic/autoguide-react — loading skeleton for Help Widget panel.
 */

export function PanelSkeleton() {
  const line = (width: string) => (
    <div
      style={{
        height: 12,
        width,
        borderRadius: 4,
        background: 'var(--ag-surface-muted)',
        marginBottom: 10,
      }}
    />
  );

  return (
    <div aria-hidden>
      {line('70%')}
      {line('100%')}
      {line('85%')}
    </div>
  );
}
